### ISSUE TITLE
Apache Compatibility, PHP Warning, @import issue

### ISSUE THREAD

**Issue by mckernanin** [stuttter/wp-enqueue-masher#1]
1. Here's an apache rule that works (mostly) for me:
   `<Directory /s/>`
   `RewriteEngine On`
   `RewriteRule ^(.*)$ ${DOCUMENT_ROOT}/wp-concat.php [L]`
   `</Directory>`
2. I'm getting this warning from PHP:
   Warning:  Header must contain a colon in public/wp-concat.php on line 310
3. It seems that an import in my child theme's style.css isn't being respected, as the parent theme styles aren't being loaded.

I'm not sure if the issues are related or not, wanted to bring them up! Happy to help troubleshoot.

**Comment by JJJ** [comment]
Hey @mckernanin. I bet this is exactly what's happening. There isn't any support built-in for handling `@import` in regards to the load order of those nested assets, and I bet something is causing a PHP error to interrupt the headers.

If you can break the `@import`'s up into separate calls to `wp_enequeue_style()`, that should bypass the issue for you, but that may not be an issue depending on your application.

I'll need to look into this a bit further, and I'll reply back if I need some help.

Thanks for letting me know.

**Comment by mckernanin** [comment]
Cool. I'll test without an import and let you know how that goes!
