### ISSUE TITLE
Update Installation - Make it clearer file location

### ISSUE THREAD

**Issue by renatonascalves** [stuttter/wp-enqueue-masher#2]
I could be dumb, but I lost around half a hour trying to make this plugin work just because of a simple misunderstanding.

The problem was here: 

- Drag ./drop-ins/wp-concat.php into the root of your WordPress installation

I thought it meant, drop the folder drop-ins, with its file, in the root of the WordPress installation. It didn't work.

Then, trying to fix it, I thought it was VVV, Nginx, fastcgi_pass, PHP, I got looking for the problem. Until just for the sake of testing, I decided to remove the drop-ins folder and add the wp-concat.php file in the root of the WP. 

Then, it works! 

So making clearer it is the file and not the folder that should be in the root of the WP installation, will make the life of dumb devs like me easier.

Awesome plugin, btw @JJJ  :)

**Comment by JJJ** [comment]
Not dumb at all. I'll tweak the verbiage in hopes of making it more clear. ❤️
